### ISSUE TITLE
Can the names/tabs shown under the Lighthouse tab be customized?

### ISSUE THREAD

**Issue by jimmy-rs** [gsoft-inc/azure-pipelines-lighthouse#10]
I ran Lighthouse on couple pages under our site. The results shown in the Lighthouse tab are `www.name.com`, `www.name.com (1)`, `www.name.com (2)` - this is very hard to identify which page the result is for. Can custom name be specified? e.g so we can get `home-page`, `marketplace`, `faq`?

**Comment by asimmon** [comment]
Hi, I just released a new version 1.0.5 which allows you to customize the tab name of task report. The new task parameter is "Report tab name override".

![image](https://user-images.githubusercontent.com/14242083/98451120-eb8cd200-2110-11eb-9145-e42a56918e21.png)
