### ISSUE TITLE
URL display on report tabs for same domain

### ISSUE THREAD

**Issue by fpl1976** [gsoft-inc/azure-pipelines-lighthouse#12]
Hello

When scoring the results for different pages of the same domain the results in the reports tab show:
`https://my.domain` `https://my.domain (2)` `https://my.domain (3)`
Is it possible to set up a title to be displayed in each tab?

Thanks

**Comment by asimmon** [comment]
Hi @fpl1976, I just released a new version 1.0.5 which allows you to customize the tab name of each task report. The new task parameter is "Report tab name override".

![image](https://user-images.githubusercontent.com/14242083/98451139-1119db80-2111-11eb-8217-197a0fbc4a1c.png)

**Comment by fpl1976** [comment]
Great @asimmon , very useful
