### ISSUE TITLE
404 on results when release has multiple agent jobs and one doesn't run

### ISSUE THREAD

**Issue by silkio** [gsoft-inc/azure-pipelines-lighthouse#15]
On a release pipeline with more than one agent task where one of the agent tasks, other than the task running lighthouse, doesn't run, the lighthouse report doesn't show.

With Lighthouse extension 1.0.5

**Steps to recreate:**

- Create a new release pipeline with an empty job
- On the first agent job change the name to "Agent Job  - not running"
- Change the "Run this job setting" to "custom condition using variable expression" and set Variable expression to eq(1,2) so that it never runs

![image](https://user-images.githubusercontent.com/6536832/101070039-b8642400-3592-11eb-86a8-8c7600524f52.png)

- Add a second "Agent job"
- On the second agent job change the name to "Agent Job  - lighthouse"
- Add the install Node.js task with version 14.15.1
- Add the lighthouse task and set the url to https://www.google.co.uk/

![image](https://user-images.githubusercontent.com/6536832/101069972-a08ca000-3592-11eb-9ba6-b9eb686ce020.png)

- Save the release pipeline
- Create a new release and let it run

**Expected behavior:**
lighthouse report shows in Lighthouse tab of "Stage 1"

**Actual behavior**
Lighthouse tab of "Stage 1" shows "404: error" despite the lighthouse task having run.

![image](https://user-images.githubusercontent.com/6536832/101070368-2c063100-3593-11eb-87b4-5796e818f094.png)

![image](https://user-images.githubusercontent.com/6536832/101070313-185aca80-3593-11eb-9cb1-6dccef5c6d5b.png)

**Comment by asimmon** [comment]
Thanks @silkio for reporting this issue, I really appreciated the reproduction steps and screenshots.

It has been fixed in commit [9bc25ff](https://github.com/gsoft-inc/azure-pipelines-lighthouse/commit/9bc25ff2528017b3acebaa30e7c345c23d13cd77) and it is already in prod.

**Comment by silkio** [comment]
Thank @asimmon, appreciate the quick turnaround and for this Azure Devops task.  It's very useful.  I've confirmed that this issue is resolved for my use case.
