### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by hjelmdal** [gsoft-inc/azure-pipelines-lighthouse#2]
Hi, 

Any plan of publishing to Marketplace, so that it can be installed on a cloud account? :-)

**Comment by Aaron007lee** [comment]
Friendly ping on this, will it become available on the Marketplace anytime soon?  thx

**Comment by asimmon** [comment]
The extension is now is publicly available at:
https://marketplace.visualstudio.com/items?itemName=GSoft.lighthouse-vsts
