### ISSUE TITLE
Pages with login Authentication

### ISSUE THREAD

**Issue by SUBHAJEETMOHANTY90** [gsoft-inc/azure-pipelines-lighthouse#22]
How to test url which require authentication? I have used your agent file.
Would you please help me understand the process to be followed. I have read the complete document of your from github.

**Comment by asimmon** [comment]
This Azure DevOps task is only a wrapper around [Google's Lighthouse](https://github.com/GoogleChrome/lighthouse). Please read their [CLI documentation](https://github.com/GoogleChrome/lighthouse#cli-options) until you find the right arguments that fit your authentication needs.

Then, provide these CLI arguments to our task.
