### ISSUE TITLE
Question: Is it possible to run the agent for desktop?

### ISSUE THREAD

**Issue by ardenne21** [gsoft-inc/azure-pipelines-lighthouse#30]
Hi, thanks for this awesome tool. 
We run a test pipeline and we saw results for the mobile version of the website. Is it available a flag or something to get results for the desktop version of the website?

**Comment by asimmon** [comment]
Hi, thanks for using our task. Based on [Lighthouse's documentation](https://github.com/GoogleChrome/lighthouse#cli-options), you must provide the CLI argument `--preset=desktop`.

Also, note that we do not support Lighthouse 10 yet (we should in a few days). If you need to use this version, please follow [this workaround](https://github.com/gsoft-inc/azure-pipelines-lighthouse/issues/31#issuecomment-1425830093) until we support it.
