### ISSUE TITLE
Question No Issue : How Do You Add This Tab

### ISSUE THREAD

**Issue by MugShotGG** [gsoft-inc/azure-pipelines-lighthouse#8]
Hey! 
Thank you so much for making this tool. Its been really nice with some of the projects ive been working on. How did you manage to add this tab into the output of the release? I've been wanting to publish info about the task out and doing so with this sort of mechanism would be much better than the write host solutions i have in place now. 
![image](https://user-images.githubusercontent.com/40046107/85149486-f94fc280-b216-11ea-886c-918984143919.png)

Thanks Again!

**Comment by asimmon** [comment]
Hi @MugShotGG, you would have to develop your very own extension that could be published inside your organization only.

There's quite a lot of learning and work to achieve this. These Microsoft resources and samples helped a lot:

https://github.com/Microsoft/vss-web-extension-sdk
Which is the SDK for developing all kinds of Azure DevOps and TFS extensions.

https://github.com/microsoft/vsts-extension-samples/tree/master/build-results-enhancer
This is the simplest "add release tab" sample, and that's where we started.

You can compare this sample with our codebase to see how we evolved from these samples.

**Comment by MugShotGG** [comment]
Thanks much! This is a great starting point for what i was wanting to do.
